data_dir: data
folder_date: '2024-10-30'
metrics_dir: metrics
model_dir: model_artifacts
predictability: 0.8
project_dir: sample/2024-10-30
resource_dir: support_files
sample_size: 10000
target_name: target
target_rate: 0.5
target_wts:
- 0.5
- 0.5
train_size: 0.8
use_case: sample
